const express = require('express');
var request = require('request');
const cors = require('cors');
const { graphqlHTTP } = require('express-graphql');
const gql = require('graphql-tag');
const { buildASTSchema } = require('graphql');

const POSTS = [
  { author: "John Doe", body: "Hello world" },
  { author: "Jane Doe", body: "Hi, planet!" },
];

const schema = buildASTSchema(gql`
  type Query {
    posts: [Post]
    post(id: ID!): Post
    hello: String
    query: [Items]
  }

  type Post {
    id: ID
    author: String
    body: String
  }

type Images { height: Int url: String width: Int }

type Followers { href: String total: Int }

type ExternalUrls { spotify: String }

type Items {
  href: String
  id: String
  name: String
  popularity: Int
  type: String
  uri: String
  images: [Images ]
  genres: [String ]
  followers: Followers
  external_urls: ExternalUrls }

type AutogeneratedMainType { total: Int
  limit: Int
  offset: Int
  previous: String
  href: String
  next: String
  items: [Items ] }
`);

const mapPost = (post, id) => post && ({ id, ...post });

const root = {
  posts: () => POSTS.map(mapPost),
  post: ({ id }) => mapPost(POSTS[id], id),
  hello: () => 'Hello world!',
  query: () => {
    return new Promise(resolve => {
      request({
        url: "https://api.spotify.com/v1/me/top/artists",
        method: "GET",
        headers: {
          'Authorization': 'Bearer ' +
            'BQCjrtvbvauFdm5PovY_C2RjCTI4VX91NpMmN8KMEhzxbjpmN8bbkum2XvxwZkVyHoHKHwgKtglIwwsGRFNoEs56mag-eu9fmz19nhXm31kXeldtX8L1P1cYtNbyGUPW8ZRvuxOGsY4HqIxIJ8CGY29mhf4VMtQArFZmcXI_PBGeStM47Qe0NmnGQCZiEJ-DINzSc3f-t37U1w9PWiPvCguM2mPs_fCxHPM5a2D86uYLNP-LXQ2PhtLjG_OStRVQMYK96dZwtL1cGFaUGKnFga88Jm7yrGwSIGOeGgwL'
        },
        json: true
      }, function (error, response, body) {
        if (!error)
          resolve(body);
      })
    }).then(value => {
      // process value here
      return value.items;
    })
  }
};

const app = express();
app.use(cors());
app.use('/graphql', graphqlHTTP({
  schema,
  rootValue: root,
  graphiql: true,
}));

const port = process.env.PORT || 4000
app.listen(port);
console.log(`Running a GraphQL API server at localhost:${port}/graphql`);
