const express = require('express');
const request = require('request');
const morgan = require('morgan')
const cors = require('cors');
const { graphqlHTTP } = require('express-graphql');
const gql = require('graphql-tag');
const { buildASTSchema } = require('graphql');

const POSTS = [
  { author: "John Doe", body: "Hello world" },
  { author: "Jane Doe", body: "Hi, planet!" },
];

const schema = buildASTSchema(gql`
  type Query {
    posts: [Post]
    post(id: ID!): Post
    hello: String
    query: [Items]
  }

  type Post {
    id: ID
    author: String
    body: String
  }

type Images { height: Int url: String width: Int }

type Followers { href: String total: Int }

type ExternalUrls { spotify: String }

type Items {
  href: String
  id: String
  name: String
  popularity: Int
  type: String
  uri: String
  images: [Images ]
  genres: [String ]
  followers: Followers
  external_urls: ExternalUrls }

type AutogeneratedMainType { total: Int
  limit: Int
  offset: Int
  previous: String
  href: String
  next: String
  items: [Items ] }
`);

const mapPost = (post, id) => post && ({ id, ...post });

const root = {
  posts: () => POSTS.map(mapPost),
  post: ({ id }) => mapPost(POSTS[id], id),
  hello: () => 'Hello world!',
  query: () => {
    return new Promise(resolve => {
      request({
        url: "https://api.spotify.com/v1/me/top/artists",
        method: "GET",
        headers: {
          'Authorization': 'Bearer ' +
            'BQDyV4wprt4p0eK5XXPG_IEsruijUV1JpNGyztoUod9wRXC-gMMWU6ZXY2FXcTgQ32CyZV1b0BTL479dWjN802-DWHnfnQp-WkYkYOnsc4iNZsm016K2UoYJM7H07E2EGfg2P1Ix0AER8UnARjCjmo9-FF3ysRMc5Rj0j1uZwk0ySSWHJ3TdqgogI_SZfwTU3o13QZxSnJqY8F6HHPqKUv5754uOODfWaGMNrLsTIpeW-tF287PwTLBwWVNyoOPGBXfGvsK8gfXNjHMYEmgI7xfmFG4569gOXlxg8jwM'
        },
        json: true
      }, function (error, response, body) {
        if (!error)
          resolve(body);
      })
    }).then(value => {
      // process value here
      return value.items;
    })
  }
};

const app = express();
app.use(cors());
app.use(morgan());
app.use('/graphql', graphqlHTTP({
  schema,
  rootValue: root,
  graphiql: true,
}));

const port = process.env.PORT || 4000
app.listen(port);
console.log(`Running a GraphQL API server at localhost:${port}/graphql`);
